<?php

use Doctrine\ORM\EntityManagerInterface;

namespace SioBundle\Repository;

/**
 * SituationDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationDetailsRepository extends \Doctrine\ORM\EntityRepository
{

    private $entityManager;

    /*
    public function __construct(EntityManagerInterface  $entityManager)
    {

        $this->entityManager =  $entityManager;

    }

    public function test()
    {

        $dql = $this->entityManager->createQuer('');

        return $dql->execute();


    }*/
}
